[server]
headless = true
enableCORS=false
port = 80


[theme]
# Primary accent color for interactive elements.
primaryColor = "#945600"

# Background color for the main content area.
backgroundColor = "#424B54"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#C75000"

# Color used for almost all text.
textColor = "#E4DFDA"